# Generated by Django 5.1.3 on 2024-11-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_tutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subjects',
            new_name='password',
        ),
    ]
