# Generated by Django 5.1.3 on 2024-11-14 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_tutor', '0003_studentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='subjects_can_teach',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='name',
        ),
        migrations.AddField(
            model_name='tutor',
            name='contact_info',
            field=models.CharField(help_text='Your contact information', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='subjects_can_teach',
            field=models.TextField(help_text='Subjects you can teach', null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='contact_info',
            field=models.CharField(help_text='Your contact information', max_length=255, null='True'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='subjects_needed',
            field=models.TextField(help_text='Subjects you need help with', null='True'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
