# Generated by Django 5.1.3 on 2024-11-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_tutor', '0005_availability_booking_event_slot_delete_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
