# Generated by Django 5.1.3 on 2024-11-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_tutor', '0007_remove_booking_status_booking_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
