# Generated by Django 5.1.3 on 2026-06-18 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_tutor', '0008_delete_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor'), ('both', 'Both')], default='student', max_length=10)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='tutor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='peer_tutor.tutor'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='peer_tutor.slot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slot',
            name='is_booked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='peer_tutor.tutor'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='subjects_needed',
            field=models.TextField(blank=True, help_text='Legacy CSV subjects field', null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subjects_can_teach',
            field=models.TextField(blank=True, help_text='Legacy CSV subjects field', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('tutor', 'date', 'start_time', 'end_time')},
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['tutor', 'date'], name='peer_tutor__tutor_i_a56a86_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['student'], name='peer_tutor__student_615ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['tutor', 'is_booked'], name='peer_tutor__tutor_i_17308f_idx'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['start_time'], name='peer_tutor__start_t_4beef3_idx'),
        ),
        migrations.AddField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='peer_tutor.tutor'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='peer_tutor__name_bca5c1_idx'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='peer_tutor.subject'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='peer_tutor.subject'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['user'], name='peer_tutor__user_id_573518_idx'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=models.Index(fields=['user'], name='peer_tutor__user_id_2a49bf_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['tutor'], name='peer_tutor__tutor_i_624064_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['student'], name='peer_tutor__student_2a1544_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('student', 'tutor')},
        ),
    ]
